# Generated by Django 6.1 on 2026-08-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prep_time', models.PositiveBigIntegerField(help_text='Preparation time in minutes')),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField(help_text='Protein in grams')),
                ('ingredients', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
