# Generated by Django 6.1 on 2026-08-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='dietary_type',
            field=models.CharField(choices=[('standard', 'No specific diet'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], default='standard', max_length=20),
        ),
    ]
