# Generated by Django 6.1 on 2026-08-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_dietary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_halal',
            field=models.BooleanField(default=True),
        ),
    ]
