# Generated by Django 6.1 on 2026-08-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_meal_is_halal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='dietary_type',
            field=models.CharField(choices=[('standard', 'No specific diet'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('halal', 'Halal-compatible')], default='standard', max_length=20),
        ),
    ]
