# Generated by Django 6.1 on 2026-09-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_meal_cuisine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='cuisine_type',
            field=models.CharField(choices=[('british', 'British'), ('italian', 'Italian'), ('mediterranean', 'Mediterranean'), ('south_asian', 'South Asian'), ('east_asian', 'East Asian'), ('mexican', 'Mexican'), ('international', 'Other / International')], default='international', max_length=30),
        ),
    ]
