# Generated by Django 6.1 on 2026-09-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_alter_meal_cuisine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='cooking_method',
            field=models.TextField(blank=True, help_text='Enter each cooking step on a separate line'),
        ),
        migrations.AddField(
            model_name='meal',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube tutorial URL'),
        ),
    ]
